# Generated by Django 4.2.4 on 2023-10-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('idCustomer', models.AutoField(primary_key=True, serialize=False)),
                ('accountState', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], max_length=9, null=True)),
                ('personalPresentation', models.TextField(null=True)),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
