# Generated by Django 4.2.4 on 2024-10-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('idCustomer', models.AutoField(primary_key=True, serialize=False)),
                ('accountState', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], max_length=9, null=True)),
                ('personalPresentation', models.TextField(null=True)),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('idPreference', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('idMedicalInformation', models.AutoField(primary_key=True, serialize=False)),
                ('allergies', models.TextField(null=True)),
                ('medicalConditions', models.TextField(null=True)),
                ('medicationIntake', models.TextField(null=True)),
                ('medicationRestriction', models.TextField(null=True)),
                ('emergencyContact', models.CharField(max_length=15, null=True)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', unique=True)),
            ],
        ),
    ]
