# Generated by Django 4.2.4 on 2023-11-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_preference_medicalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='idCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', unique=True),
        ),
    ]
