# Generated by Django 4.2.4 on 2023-10-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('idLanguage', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=80)),
                ('lastNames', models.CharField(max_length=80)),
                ('password', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('profilePhoto', models.CharField(max_length=200, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageUser',
            fields=[
                ('idLanguageUser', models.AutoField(primary_key=True, serialize=False)),
                ('idLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
